// import fs from "fs";

// const clear = (str: string) => {
//   if (!str) return "";
//   return str.replace(/œ/g, "oe").replace(/[^\x00-\xFF]/g, "");
// };

// const self = fs.readFileSync("./server/constData/vegan.ts").toString();
// fs.writeFileSync("./server/constData/vegan.ts", clear(self));

interface veganFood {
  en: string[];
  fr: string[];
}

export const veganUnallowedFood: veganFood = {
  en: [
    //Meat
    "beef",
    "lamb",
    "pork",
    "veal",
    "horse",
    "organ",
    "meat",
    "wild meat",
    "leather",
    //Poultry
    "chicken",
    "turkey",
    "goose",
    "duck",
    "quail",
    //Fish
    "salmon",
    "cod",
    "herring",
    "Mahi-mahi",
    "fish",
    "mackerel",
    "perch",
    "trout",
    "sardines",
    "bass",
    "tuna",
    "pollock",
    "arctic char",
    //Dairy
    "milk",
    "yogurt",
    "cheese",
    "butter",
    "cream",
    "ice cream",
    //Bee products
    "honey",
    "bee pollen",
    "royal jelly",
    //Additives
    "E120",
    "E322",
    "E422",
    "E471",
    "E542",
    "E631",
    "E901",
    "E904",
    "cochineal",
    "carmine",
    "gelatin",
    "isinglass",
    "castoreum",
    "shellac",
    "vitamin D3",
    "casein",
    "lactose",
    // other

    "abalone",
    "acetate",
    "acetylated hydrogenated lard glyceride",
    "acetylated lanolin",
    "acetylated lanolin alcohol",
    "acetylated lanolin ricinoleate",
    "acetylated tallow",
    "acid",
    "acidophilus milk",
    "adrenaline",
    "adrenals of cattle",
    "adrenals of hogs",
    "adrenals of sheep",
    "afterbirth",
    "alanine",
    "albumen",
    "albumin",
    "alcloxa",
    "aldioxa",
    "aliphatic alcohol",
    "allantoin",
    "alligator",
    "alligator skin",
    "alpha-hydroxy acids",
    "ambergris",
    "amerachol",
    "amerchol l101",
    "aminiuccinate acid",
    "amino acids",
    "aminosuccinate acid",
    "ammonium caseinate",
    "ammonium hydrolyzed protein",
    "amniotic fluid",
    "ampd isoteric hydrolyzed animal protein",
    "amylase",
    "anchovies",
    "anchovy",
    "angora",
    "animal bones",
    "animal collagen amino acids",
    "animal fat",
    "animal fats and oils",
    "animal hair",
    "animal keratin amino acids",
    "animal oil",
    "animal placenta",
    "animal protein derivative",
    "animal tissue extract",
    "arachidonic acid",
    "arachidyl proprionate",
    "aspartic acid",
    "aspic",
    "astrakhan",
    "back bacon",
    "back fat",
    "bacon",
    "bass",
    "batyl alcohol",
    "batyl isostearate",
    "bear",
    "bee pollen",
    "bee products",
    "beef",
    "beef heart",
    "beef liver",
    "beef tongue",
    "beepollen",
    "beeswax",
    "beeswax honeycomb",
    "belly bacon",
    "benzyltrimonium hydrolyzed animal protein",
    "biotin vitamin h vitamin b factor",
    "bison",
    "blood",
    "blood plasma fractionation",
    "blood tongue",
    "boar bristles",
    "boiled ham",
    "bone ash",
    "bone char",
    "bone char(coal)/boneblack",
    "bone charcoal",
    "bone earth",
    "bone meal",
    "bone phosphate",
    "bone soup",
    "bone/bonemeal",
    "boneblack",
    "bonito",
    "bovine serum albumin",
    "brain extract",
    "bratwurst",
    "brawn",
    "breakfast bacon",
    "bresaola",
    "bristle",
    "bruehwurst",
    "buffalo",
    "buffalo milk",
    "bushmeat",
    "butter",
    "butter fat",
    "butter solids",
    "buttermilk",
    "buttermilk powder",
    "c30-46 piscine oil",
    "calamari",
    "calciferol",
    "calciferool",
    "calcium caseinate",
    "calf liver",
    "calfskin",
    "calfskin extract",
    "camel milk",
    "canadian bacon",
    "cantharides tincture",
    "capiz",
    "capryl betaine",
    "caprylamine oxide",
    "caprylic acid",
    "caprylic triglyceride",
    "carbamide",
    "caribou",
    "carmine",
    "carmine cochineal carminic acid",
    "carmine/carminic acid",
    "carmine: cochineal. carminic acid",
    "carminic",
    "carminic acid",
    "carotene provitamin a beta carotene",
    "carp",
    "casein",
    "casein caseinate sodium caseinate",
    "caseinate",
    "caseinogen",
    "cashmere",
    "castor castoreum",
    "castoreum",
    "catfish",
    "catgut",
    "catharidin",
    "caviar(e)",
    "cera flava",
    "cerebrosides",
    "certain additives",
    "ceteth-02",
    "ceteth-1",
    "ceteth-10",
    "ceteth-2",
    "ceteth-30",
    "ceteth-4",
    "ceteth-6",
    "cetyl alcohol",
    "cetyl lactate",
    "cetyl myristate",
    "cetyl palmitate",
    "chamois",
    "cheese",
    "chicken",
    "chicken breast",
    "chicken liver",
    "chicken loaf",
    "chipped ham",
    "chitin",
    "chitosan",
    "cholecalciferol",
    "cholesterin",
    "cholesterol",
    "choline bitartrate",
    "chondroitin",
    "chopped ham",
    "chorizo",
    "chymotrypsin",
    "civet",
    "clarified butter",
    "clotted cream",
    "cochineal",
    "cod",
    "cod liver oil",
    "cold cuts",
    "coleth-24",
    "collagen",
    "collagen hydrolysate",
    "colors dyes",
    "condensed milk",
    "confectioners glaze",
    "cooked ham",
    "cooked meats",
    "coral",
    "corned beef",
    "cornish game hen",
    "cortico steroid",
    "corticosteroid",
    "cortisone",
    "cortisone corticosteroid",
    "cortisone: see cortico steroid.",
    "cotechino",
    "cottage cheese",
    "crab",
    "crabmeat",
    "crawfish",
    "crayfish",
    "cream",
    "crustacean shellfish",
    "curds",
    "custard",
    "cysteine, l-form",
    "cystine",
    "dark meat",
    "dashi",
    "dea-oleth-10 phosphate",
    "deer",
    "deer meat",
    "delactosed whey",
    "deli meats",
    "demineralized whey",
    "deoxyribonucleic acid",
    "desamido animal collagen",
    "desamidocollagen",
    "devon",
    "dexpanthenol",
    "dicapryloyl cystine",
    "diethylene tricaseinamide",
    "diglycerides",
    "dihydrocholesterol",
    "dihydrocholesterol octyledecanoate",
    "dihydrocholeth-15",
    "dihydrocholeth-30",
    "dihydrogenated tallow benzylmoniumchloride",
    "dihydrogenated tallow methylamine",
    "dihydrogenated tallow phthalate",
    "dihydroxyethyl tallow amine oxide",
    "dimethyl hydrogenated tallowamine",
    "dimethyl stearamine",
    "dimethyl tallowamine",
    "disodium hydrogenatedtallowglutamate",
    "disodium tallamido mea-sulfosuccinate",
    "disodium tallowaminodipropionate",
    "ditallowdimonium chloride",
    "dna",
    "down",
    "dried buttermilk",
    "dried egg yolk",
    "dry milk solids",
    "dry whole milk",
    "duck",
    "duck bacon",
    "duck liver",
    "duodenum substances",
    "dutch loaf",
    "dyes",
    "e120",
    "e441",
    "e542",
    "e904",
    "e913",
    "edible bone phosphate",
    "egg",
    "egg albumen",
    "egg albumen/albumin",
    "egg oil",
    "egg powder",
    "egg protein",
    "egg whites",
    "egg yolk",
    "egg yolk extract",
    "egg yolks",
    "eggs",
    "elastin",
    "elk bacon",
    "embryo extract",
    "emu",
    "emu oil",
    "epiderm oil r",
    "ergisterol",
    "ergocalciferol",
    "ergosterol",
    "estradiol",
    "estradiol benzoate",
    "estrogen",
    "estrogen estradiol",
    "estrogen/estradiol",
    "estrone",
    "ethyl ester of hydrolyzed animal protein",
    "ethyl morrhuatelipineate",
    "ethylarachidonate",
    "ethylene dehydrogenated tallowamide",
    "evaporated milk",
    "ewe milk",
    "fat-free milk",
    "fat-free yogurt",
    "fats",
    "fatty acids",
    "fd and c colors",
    "feathers",
    "felt",
    "fermented camel milk",
    "fermented cream",
    "fermented milk",
    "fish",
    "fish glycerides",
    "fish liver",
    "fish liver oil",
    "fish livers",
    "fish oil",
    "fish sauce",
    "fish scales",
    "fishsauce",
    "fletan oil",
    "fur",
    "gel",
    "gelatin",
    "gelatin gel",
    "gelatin(e)",
    "gelbwurst",
    "ghee",
    "gizzards",
    "glucosamine",
    "glucose tyrosinase",
    "glucuronic acid",
    "glutamic acid",
    "glycerides",
    "glycerin glycerol",
    "glycerol",
    "glyceryl lanolate",
    "glyceryls",
    "glycogen",
    "glycreth-26",
    "goat",
    "goat cheese",
    "goat milk",
    "goose",
    "goose insulating feathers",
    "goose liver",
    "ground beef",
    "grouse",
    "guanine",
    "guanine pearl essence",
    "guanine/pearl essence",
    "guinea hen",
    "gypsy bacon",
    "haddock",
    "hair from hogs",
    "halibut",
    "ham",
    "ham and cheese loaf",
    "head cheese",
    "heavy cream",
    "heptylundecanol",
    "hide",
    "hide glue",
    "homogenized milk",
    "honey",
    "honeycomb",
    "horse",
    "horse hair",
    "horseflesh",
    "horsehair",
    "hot dog",
    "human placental protein",
    "human umbilical extract",
    "hyaluronic acid",
    "hydrlyzed human placental protein",
    "hydrocortisone",
    "hydrogenated animal glyceride",
    "hydrogenated ditallow amine",
    "hydrogenated honey",
    "hydrogenated laneth-20",
    "hydrogenated laneth-25",
    "hydrogenated laneth-5",
    "hydrogenated lanolin",
    "hydrogenated lanolin alcohol",
    "hydrogenated lard glyceride",
    "hydrogenated shark-liver oil",
    "hydrogenated tallow acid",
    "hydrogenated tallow betaine",
    "hydrogenated tallow glyceride",
    "hydrolyzed animal elastin",
    "hydrolyzed animal keratin",
    "hydrolyzed animal protein",
    "hydrolyzed casein",
    "hydrolyzed elastin",
    "hydrolyzed keratin",
    "hydrolyzed milk protein",
    "hydrolyzed silk",
    "hydroxylated lanolin",
    "ice cream",
    "imidazolidinyl urea",
    "insulin",
    "iron caseinate",
    "isinglass",
    "isobutylated lanolin",
    "isopropyl lanolate",
    "isopropyl myristate",
    "isopropyl tallowatelsopropyl lanolate",
    "isopropylpalmitate",
    "isostearic hydrolyzed animal protein",
    "isostearoyl hydrolyzed animal protein",
    "jagdwurst",
    "jowl",
    "kangaroo",
    "katsuobushi (okaka)",
    "keratin",
    "keratinamino acids",
    "l-cysteine",
    "l-form",
    "l-form: see cysteine.",
    "l-lactic acid",
    "lacotse-reduced milk",
    "lactalbumin",
    "lactic yeasts",
    "lacticacid",
    "lactoferrin",
    "lactoglobulin",
    "lactose",
    "lactose-free milk",
    "lactulose",
    "lamb",
    "lamb bacon",
    "laneth",
    "laneth-10",
    "laneth-11",
    "laneth-12",
    "laneth-13",
    "laneth-14",
    "laneth-15",
    "laneth-16",
    "laneth-17",
    "laneth-18",
    "laneth-19",
    "laneth-20",
    "laneth-21",
    "laneth-22",
    "laneth-23",
    "laneth-24",
    "laneth-25",
    "laneth-26",
    "laneth-27",
    "laneth-28",
    "laneth-29",
    "laneth-30",
    "laneth-31",
    "laneth-32",
    "laneth-33",
    "laneth-34",
    "laneth-35",
    "laneth-36",
    "laneth-37",
    "laneth-38",
    "laneth-39",
    "laneth-40",
    "laneth-5",
    "laneth-6",
    "laneth-7",
    "laneth-8",
    "laneth-9",
    "laneth-9 acetate",
    "laneth10 acetate",
    "lanogene",
    "lanoinamidedea",
    "lanolin",
    "lanolin acid",
    "lanolin acid: see lanolin.",
    "lanolin alcohol",
    "lanolin alcohols",
    "lanolin alcohols: see lanolin.",
    "lanolin lanolin acids wool fat wool wax",
    "lanolin linoleate",
    "lanolin oil",
    "lanolin ricinoleate",
    "lanolin wax",
    "lanolin(e)",
    "lanolin: lanolin acid",
    "lanosterol",
    "lanosterol: see lanolin.",
    "lanosterols",
    "lard",
    "lard glyceride",
    "lauroyl hydrolyzed animal protein",
    "leather",
    "leather suede calfskin sheepskinalligator skin other types of skin",
    "lecithin cholinebitartrate",
    "leucine",
    "linoleic acid",
    "lipase",
    "lipids",
    "lipoids lipids",
    "liver",
    "liver extract",
    "liverwurst",
    "lobster",
    "low fat milk",
    "low fat yogurt",
    "lunasponge",
    "luncehon loaf",
    "lunch meats",
    "luncheon meats",
    "lysine",
    "mackerel",
    "magnesium caseinate",
    "malted milk",
    "mammarian extract",
    "marine oil",
    "marrow soup",
    "mayonnaise",
    "mea-hydrolyzed animal protein",
    "meat",
    "meat loaf",
    "meatball",
    "mechanically separated chicken",
    "methionine",
    "mettwurst",
    "milk",
    "milk chocolate",
    "milk derivative",
    "milk of mammals",
    "milk protein",
    "milk skin",
    "milk sugar",
    "milkfat",
    "milkpowder",
    "minced beef",
    "minced meat",
    "mink oil",
    "minkamidopropyl diethylamine",
    "mohair",
    "molluscan shellfish",
    "monkfish",
    "mono and di-glycerides",
    "monoglycerides glycerides",
    "monoglycerides glycerides (see glycerin)",
    "moose",
    "mortadella",
    "mossbunker oil",
    "mullet",
    "muscle extract",
    "musk",
    "musk (oil)",
    "musk ambrette",
    "mussel",
    "mussels",
    "mutton",
    "myristal ether sulfate",
    "myristate acid",
    "myristic acid",
    "myristoyl hydrolyzed animal protein",
    "myristyl",
    "myristyls",
    "natural butter flavor",
    "natural flavorings",
    "natural red 4",
    "natural sources",
    "neck",
    "nonfat milk",
    "note:",
    "nougat",
    "nucleicacids",
    "ocenol",
    "octopus",
    "octyl dodecanol",
    "oils",
    "oleamidopropyl dimethylamine hydrolyzed animal protein",
    "oleic acid",
    "oleoic oil",
    "oleostearin",
    "oleostearine",
    "oleoyl hydrolyzed animal protein",
    "oleths",
    "oleyl arachidate",
    "oleyl betatine",
    "oleyl imidazoline",
    "oleyl lanolate",
    "oleyl myristate",
    "oleyl oleate",
    "oleyl stearate",
    "oleylalcohol ocenol",
    "oleylimidazoline",
    "omega-3 fatty acids",
    "opossum",
    "organ meat",
    "organ meats",
    "organs",
    "ostrich",
    "ovalbumin",
    "ovarian extract",
    "ox bile",
    "oxgall",
    "oyster",
    "palmitamide",
    "palmitamine",
    "palmitate",
    "palmitic acid",
    "palmitoyl hydrolyzed milk protein",
    "palmitoyl hydrolyzedanimal protein",
    "pancetta",
    "panthenol dexpanthenol vitamin b-complex factor provitamin b-5",
    "panthenyl",
    "paracasein",
    "partridge",
    "pasteurized milk",
    "pearl",
    "pearl essence",
    "pentahydrosqualene",
    "pepsin",
    "perhydrosqualene",
    "pharmaceutical glaze",
    "pheasant",
    "picnic shoulder",
    "pigskin extract",
    "placenta",
    "placenta placenta polypeptides protein afterbirth",
    "placenta polypeptides protein",
    "placental enzymes",
    "placental extract",
    "placental protein",
    "plaice",
    "pogy oil",
    "pollock",
    "poltethylene cetyl ether",
    "polyglycerol",
    "polyglyceryl-2lanolin alcohol ether",
    "polypeptides",
    "polypeptides protein",
    "polysorbates",
    "polytetylene glycerol/glycol/peg",
    "porcine pancreas",
    "pork",
    "pork fat",
    "pork roll",
    "potassium caseinate",
    "potassium tallowate",
    "potassium undecylenoyl hydrolyzed animal protein",
    "poultry",
    "ppg-12-peg-50 lanolin",
    "ppg-2,-5, -10. -20, -30 lanolinalcohol ethers",
    "ppg-30 lanolin ether",
    "prawn",
    "pregnenolone acetate",
    "pristane",
    "progesterone",
    "propolis",
    "prosciutto",
    "provitamin a",
    "provitamin b-5",
    "provitamin d-2",
    "purcelline oil syn",
    "quail",
    "quaternium 27",
    "rabbit",
    "red meat",
    "reduced fat milk",
    "reduced fat yogurt",
    "rennet",
    "rennet casein",
    "rennet rennin",
    "rennin",
    "resinous glaze",
    "reticulin",
    "retinol",
    "ribonucleic acid",
    "rna ribonucleic acid",
    "roast beef",
    "roast pork",
    "roe",
    "royal jelly",
    "sable",
    "sable brushes",
    "saccharide hydrolysate",
    "saccharide isomerate",
    "salami",
    "salceson",
    "salmon",
    "sardine",
    "sausage",
    "sausages",
    "scallop",
    "scallops",
    "sea sponge",
    "sea turtle oil",
    "seasponge",
    "serum albumin",
    "serum proteins",
    "shark liver oil",
    "shark-liver oil",
    "sheep milk",
    "sheepskin",
    "shellac",
    "shellac resinous glaze",
    "shellac wax",
    "shoulder",
    "shrimp",
    "shrimph",
    "side bacon",
    "silk",
    "silk amino acids",
    "silk powder",
    "silk silk powder",
    "skim milk",
    "slab bacon",
    "sliced meats",
    "smoked ham",
    "snail",
    "snails",
    "snake",
    "snapper",
    "sodium / tea-lauroyl hydrolyzed animal protein",
    "sodium / tea-undecylenoyl hydrolyzed animal protein",
    "sodium caseinate",
    "sodium coco-hydrolyzed animal protein",
    "sodium soya hydrolyzed animal protein",
    "sodium tallow sulfate",
    "sodium tallowate",
    "sodium undecylenate",
    "sodiumsteroyl lactylate",
    "soluble  collagen",
    "sour cream",
    "sour milk",
    "sour milk solids",
    "soured milk",
    "soya hydroxyethyl imidazoline",
    "sperm oil",
    "sperm whale intestines",
    "spermaceti",
    "spermaceticetyl palmitate sperm oil",
    "spleen extract",
    "sponge (luna and sea)",
    "squab",
    "squalane",
    "squalene",
    "squid",
    "squirrel",
    "steak",
    "stearamide",
    "stearamine",
    "stearamine oxide",
    "stearates",
    "stearic acid",
    "stearic hydrazide",
    "stearin",
    "stearone",
    "stearoxytrimethylsilane",
    "stearoyl lactylic acid",
    "stearyl acetate",
    "stearyl alcohol sterols",
    "stearyl betaine",
    "stearyl caprylate",
    "stearyl citrate",
    "stearyl glycyrrhetinate",
    "stearyl heptanoate",
    "stearyl imidazoline",
    "stearyl octanoate",
    "stearyl stearate",
    "stearyldimethyl amine",
    "steroids sterols",
    "sterols",
    "stewing steak",
    "stilton",
    "streaky bacon",
    "suede",
    "sweet dairy whey",
    "sweet whey",
    "sweetbreads",
    "sweetened condensed milk",
    "swordfish",
    "tallow",
    "tallow acid",
    "tallow amide",
    "tallow amine",
    "tallow amine oxide",
    "tallow fatty alcohol",
    "tallow glycerides",
    "tallow hydroxyethal imidazoline",
    "tallow imidazoline",
    "tallow tallow fatty alcohol stearic acid",
    "tallow trimonium chloride - tallow",
    "tallowamidopropylamine oxide",
    "talloweth-6",
    "tallowmide dea and mea",
    "tallowmidopropyl hydroxysultaine",
    "tallowminopropylamine",
    "tallowmphoacete",
    "tea-abietoyl hydrolyzedanimal protein",
    "tea-coco hydrolyzed animal protein",
    "tea-lauroyl animal collagen amino acids",
    "tea-lauroyl animal keratin amino acids",
    "tea-myristol hydrolyzed animal protein",
    "tea-undecylenoyl hydrolyzed animal protein",
    "testicular extract",
    "threonine",
    "thuringian sausage",
    "tilapia",
    "tongue",
    "triethonium hydrolyzed animal protein ethosulfate",
    "trilaneth-4phosphate",
    "tripe",
    "triterpene alcohols",
    "trout",
    "trypsin",
    "tuna",
    "turkey",
    "turkey bacon",
    "turkey breast",
    "turtle",
    "turtle oil",
    "sea turtle oil",
    "tyrosine",
    "un-homogenized milk",
    "urea",
    "urea carbamide",
    "uric acid",
    "uric acid from cows",
    "uricacid",
    "urine",
    "veal",
    "veal loaf",
    "venison",
    "vitamin a",
    "vitamin b-complex factor",
    "vitamin d ergocalciferol vitamin d",
    "vitamin d3",
    "vitamin h",
    "vitaminb",
    "vitaminb factor",
    "volaise",
    "whey",
    "whey powder",
    "whey protein",
    "whipped cream",
    "whipped topping",
    "white meat",
    "whole milk",
    "whole milk yogurt",
    "wild boar",
    "wild meat",
    "wool",
    "wool fat",
    "wool wax",
    "wool wax alcohols",
    "yoghurt",
    "yogurt",
    "zinc caseinate",
    "zinc hydrolyzed animal protein",
  ],
  fr: [
    "boeuf",
    "agneau",
    "porc",
    "veau",
    "cheval",
    "organe",
    "viande",
    "cuir",
    //Poultry
    "poulet",
    "dinde",
    "oie",
    "canard",
    "Caille",
    //Fish
    "saumon",
    "morue",
    "hareng",
    "Mahi-mahi",
    "poisson",
    "maquereau",
    "perche",
    "truite",
    "sardine",
    "thon",
    "goberge",
    "omble chevalier",
    //Dairy
    "lait",
    "yahourt",
    "fromage",
    "beure",
    "crème",
    "crème glacé",
    //Bee products
    "miel",
    "pollen",
    "gelé royale",
    //Additives
    "E120",
    "E322",
    "E422",
    "E471",
    "E542",
    "E631",
    "E901",
    "E904",
    "cochenille",
    "carmin",
    "gelatine",
    "ichtyocolle",
    "castoreum",
    "laque",
    "D3",
    "caséine",
    "lactose",
    //Viande
    "boeuf",
    "agneau",
    "porc",
    "veau",
    "cheval",
    "organe",
    "viande",
    "viande sauvage",
    "cuir",
    //Poulet
    "poulet",
    "dinde",
    "oie",
    "canard",
    "caille",
    "saumon",
    "morue",
    "hareng",
    "Mahi-mahi",
    "poisson",
    "maquereau",
    "perche",
    "truite",
    "sardines",
    "bar",
    "thon",
    "colin",
    "omble chevalier",
    "lait",
    "yaourt",
    "fromage",
    "beurre",
    "crème",
    "crème glacée",
    //Produits d'abeille
    "miel",
    "pollen d'abeille",
    "gelée royale",
    //Additifs
    "E120",
    "E322",
    "E422",
    "E471",
    "E542",
    "E631",
    "E901",
    "E904",
    "cochenille",
    "carmin",
    "gélatine",
    "isinglass",
    "castoréum",
    "gomme-laque",
    "vitamine D3",
    "caséine",
    "lactose",
    // autres

    "ormeau",
    "acétate",
    "glycéride de saindoux hydrogéné acétylé",
    "lanoline acétylée",
    "alcool de lanoline acétylé",
    "ricinoléate de lanoline acétylée",
    "suif acétylé",
    "acide",
    "lait acidophilus",
    "adrénaline",
    "surrénales de bovins",
    "surrénales de porcs",
    "surrénales de moutons",
    "post-naissance",
    "alanine",
    "albumine",
    "albumine",
    "alcloxa",
    "aldioxa",
    "alcool aliphatique",
    "allantoïne",
    "alligator",
    "peau d'alligator",
    "acides alpha-hydroxy",
    "ambre gris",
    "amerachol",
    "amerchol l101",
    "acide amino-uccinique",
    "acides aminés",
    "acide aminosuccinate",
    "caséinate d'ammonium",
    "protéine hydrolysée d'ammonium",
    "liquide amniotique",
    "protéine animale hydrolysée ampd isotérique",
    "amylase",
    "anchois",
    "anchois",
    "angora",
    "os d'animaux",
    "acides aminés de collagène animal",
    "graisse animale",
    "graisses et huiles animales",
    "poils d'animaux",
    "acides aminés de kératine animale",
    "huile animale",
    "placenta animal",
    "dérivé de protéine animale",
    "extrait de tissu animal",
    "acide arachidonique",
    "proprionate d'arachidyle",
    "acide aspartique",
    "aspic",
    "astrakan",
    "bacon",
    "lard dorsal",
    "bacon",
    "basse",
    "alcool batylique",
    "isostéarate de batyle",
    "ours",
    "pollen d'abeille",
    "produits de l'abeille",
    "boeuf",
    "coeur de boeuf",
    "foie de boeuf",
    "langue de boeuf",
    "beepollen",
    "cire d'abeille",
    "cire d'abeille en nid d'abeille",
    "bacon de poitrine",
    "protéine animale hydrolysée au benzyltrimonium",
    "biotine vitamine h vitamine b facteur",
    "bison",
    "sang",
    "fractionnement du plasma sanguin",
    "langue de sang",
    "soies de sanglier",
    "jambon cuit",
    "cendre d'os",
    "charbon d'os",
    "charbon d'os",
    "noir d'os",
    "charbon d'os",
    "terre d'os",
    "poudre d'os",
    "phosphate d'os",
    "soupe d'os",
    "os/farine d'os",
    "boneblack",
    "bonite",
    "albumine de sérum bovin",
    "extrait de cerveau",
    "bratwurst",
    "brawn",
    "bacon de petit-déjeuner",
    "bresaola",
    "bristle",
    "bruehwurst",
    "buffle",
    "lait de buffle",
    "viande de brousse",
    "beurre",
    "graisse de beurre",
    "matières solides du beurre",
    "babeurre",
    "babeurre en poudre",
    "huile de piscine c30-46",
    "calmar",
    "calciférol",
    "calciférol",
    "caséinate de calcium",
    "foie de veau",
    "peau de veau",
    "extrait de peau de veau",
    "lait de chamelle",
    "bacon canadien",
    "teinture de cantharides",
    "capiz",
    "capryl betaine",
    "oxyde de caprylamine",
    "acide caprylique",
    "triglycéride caprylique",
    "carbamide",
    "caribou",
    "carmin",
    "carmin cochineal acide carminique",
    "carmin/acide carminique",
    "carmin : cochenille. acide carminique",
    "carminique",
    "acide carminique",
    "carotène provitamine a bêta carotène",
    "carpe",
    "caséine",
    "caséinate de caséine, caséinate de sodium",
    "caséinate",
    "caséinogène",
    "cachemire",
    "castor",
    "castoreum",
    "castoréum",
    "poisson-chat",
    "catgut",
    "catharidine",
    "caviar(e)",
    "cera flava",
    "cérébrosides",
    "certains additifs",
    "ceteth-02",
    "ceteth-1",
    "ceteth-10",
    "ceteth-2",
    "ceteth-30",
    "ceteth-4",
    "ceteth-6",
    "alcool cétylique",
    "lactate de cétyle",
    "myristate de cétyle",
    "palmitate de cétyle",
    "chamois",
    "fromage",
    "poulet",
    "poitrine de poulet",
    "foie de poulet",
    "pain de poulet",
    "jambon fumé",
    "chitine",
    "chitosan",
    "cholécalciférol",
    "cholestérine",
    "cholestérol",
    "bitartrate de choline",
    "chondroïtine",
    "jambon haché",
    "chorizo",
    "chymotrypsine",
    "civette",
    "beurre clarifié",
    "crème caillée",
    "cochenille",
    "morue",
    "huile de foie de morue",
    "charcuterie",
    "coleth-24",
    "collagène",
    "hydrolysat de collagène",
    "colorants",
    "lait condensé",
    "glaçage de confiseur",
    "jambon cuit",
    "viandes cuites",
    "corail",
    "corned beef",
    "poule de Cornouailles",
    "cortico stéroïde",
    "corticostéroïde",
    "cortisone",
    "cortisone corticostéroïde",
    "cortisone : voir cortico stéroïde.",
    "cotechino",
    "fromage blanc",
    "crabe",
    "écrevisse",
    "écrevisse",
    "crème",
    "crustacés",
    "lait caillé",
    "crème anglaise",
    "cystéine, l-form",
    "cystine",
    "viande brune",
    "dashi",
    "phosphate dea-oleth-10",
    "cerf",
    "viande de cerf",
    "lactosérum délactosé",
    "charcuterie",
    "lactosérum déminéralisé",
    "acide désoxyribonucléique",
    "collagène animal désamidé",
    "désamidocollagène",
    "devon",
    "dexpanthénol",
    "dicapryloyl cystine",
    "diéthylène tricaséinamide",
    "diglycérides",
    "dihydrocholestérol",
    "octyledécanoate de dihydrocholestérol",
    "dihydrocholeth-15",
    "dihydrocholeth-30",
    "chlorure de benzylmonium de suif dihydrogéné",
    "méthylamine de suif dihydrogéné",
    "phtalate de suif dihydrogéné",
    "oxyde d'amine de suif dihydroxyéthyl",
    "suif hydrogéné diméthylamine",
    "diméthyl stéaramine",
    "diméthyl tallowamine",
    "Glutamate de suif hydrogéné disodique",
    "mea-sulfosuccinate de tallamido disodique",
    "tallowaminodipropionate disodique",
    "chlorure de disodiumdimonium",
    "dna",
    "duvet",
    "babeurre séché",
    "jaune d'oeuf séché",
    "matières sèches du lait",
    "lait entier sec",
    "canard",
    "bacon de canard",
    "foie de canard",
    "substances duodénales",
    "pain hollandais",
    "colorants",
    "e120",
    "e441",
    "e542",
    "e904",
    "e913",
    "phosphate d'os comestible",
    "oeuf",
    "albumine d'oeuf",
    "albumine d'oeuf/albumine",
    "huile d'oeuf",
    "poudre d'oeuf",
    "protéines d'oeuf",
    "blanc d'oeuf",
    "jaune d'oeuf",
    "extrait de jaune d'oeuf",
    "jaune d'oeuf",
    "oeufs",
    "élastine",
    "bacon d'élan",
    "extrait d'embryon",
    "émeu",
    "huile d'émeu",
    "huile d'épiderme r",
    "ergistérol",
    "ergocalciférol",
    "ergostérol",
    "estradiol",
    "benzoate d'estradiol",
    "oestrogène",
    "oestrogène/estradiol",
    "oestrogène/estradiol",
    "estrone",
    "ester éthylique de protéine animale hydrolysée",
    "morrhuatelipineate d'éthyle",
    "éthylarachidonate",
    "tallowamide déshydrogénée par éthylène",
    "lait évaporé",
    "lait de brebis",
    "lait sans matières grasses",
    "yaourt sans matières grasses",
    "graisses",
    "acides gras",
    "couleurs fd et c",
    "plumes",
    "feutre",
    "lait de chamelle fermenté",
    "crème fermentée",
    "lait fermenté",
    "poisson",
    "glycérides de poisson",
    "foie de poisson",
    "huile de foie de poisson",
    "foies de poisson",
    "huile de poisson",
    "sauce de poisson",
    "écailles de poisson",
    "fishsauce",
    "huile de fletan",
    "fourrure",
    "gel",
    "gélatine",
    "gelée de gélatine",
    "gélatine(e)",
    "gelbwurst",
    "ghee",
    "gésiers",
    "glucosamine",
    "glucose tyrosinase",
    "acide glucuronique",
    "acide glutamique",
    "glycérides",
    "glycérine glycérol",
    "glycérol",
    "glyceryl lanolate",
    "glycérols",
    "glycogène",
    "glycréth-26",
    "chèvre",
    "fromage de chèvre",
    "lait de chèvre",
    "oie",
    "plumes isolantes d'oie",
    "foie d'oie",
    "viande de boeuf hachée",
    "grouse",
    "guanine",
    "essence de perle de guanine",
    "essence de guanine/perle",
    "pintade",
    "bacon de gitan",
    "haddock",
    "poils de porcs",
    "flétan",
    "jambon",
    "pain de jambon et fromage",
    "fromage de tête",
    "crème épaisse",
    "heptylundecanol",
    "hide",
    "colle à peau",
    "lait homogénéisé",
    "miel",
    "nid d'abeille",
    "cheval",
    "crin de cheval",
    "chair de cheval",
    "crin de cheval",
    "hot dog",
    "protéine placentaire humaine",
    "extrait ombilical humain",
    "acide hyaluronique",
    "protéine placentaire humaine hydrolysée",
    "hydrocortisone",
    "glycéride animal hydrogéné",
    "ditallow amine hydrogénée",
    "miel hydrogéné",
    "laneth-20 hydrogéné",
    "laneth-25 hydrogéné",
    "laneth-5 hydrogéné",
    "lanoline hydrogénée",
    "alcool de lanoline hydrogéné",
    "glycéride de saindoux hydrogéné",
    "huile de foie de requin hydrogénée",
    "acide de suif hydrogéné",
    "bétaïne de suif hydrogéné",
    "glycéride de suif hydrogéné",
    "élastine animale hydrolysée",
    "kératine animale hydrolysée",
    "protéine animale hydrolysée",
    "caséine hydrolysée",
    "élastine hydrolysée",
    "kératine hydrolysée",
    "protéine de lait hydrolysée",
    "soie hydrolysée",
    "lanoline hydroxylée",
    "crème glacée",
    "imidazolidinyl urée",
    "insuline",
    "caséinate de fer",
    "isinglass",
    "lanoline isobutylée",
    "isopropyl lanolate",
    "myristate d'isopropyle",
    "tallowatelsopropyl lanolate",
    "palmitate d'isopropyle",
    "protéine animale hydrolysée isostéarique",
    "protéine animale hydrolysée isostéaroyle",
    "jagdwurst",
    "jowl",
    "kangourou",
    "katsuobushi (okaka)",
    "kératine",
    "acides aminés de kératine",
    "l-cystéine",
    "l-form",
    "l-form : voir cystéine.",
    "acide l-lactique",
    "lait réduit en lacotse",
    "lactalbumine",
    "levures lactiques",
    "acide lactique",
    "lactoferrine",
    "lactoglobuline",
    "lactose",
    "lait sans lactose",
    "lactulose",
    "agneau",
    "bacon d'agneau",
    "laneth",
    "laneth-10",
    "laneth-11",
    "laneth-12",
    "laneth-13",
    "laneth-14",
    "laneth-15",
    "laneth-16",
    "laneth-17",
    "laneth-18",
    "laneth-19",
    "laneth-20",
    "laneth-21",
    "laneth-22",
    "laneth-23",
    "laneth-24",
    "laneth-25",
    "laneth-26",
    "laneth-27",
    "laneth-28",
    "laneth-29",
    "laneth-30",
    "laneth-31",
    "laneth-32",
    "laneth-33",
    "laneth-34",
    "laneth-35",
    "laneth-36",
    "laneth-37",
    "laneth-38",
    "laneth-39",
    "laneth-40",
    "laneth-5",
    "laneth-6",
    "laneth-7",
    "laneth-8",
    "laneth-9",
    "acétate de laneth-9",
    "acétate de laneth-10",
    "lanogène",
    "lanoinamidedea",
    "lanoline",
    "acide lanoline",
    "acide lanoline : voir lanoline.",
    "alcool de lanoline",
    "alcools de lanoline",
    "alcools de lanoline : voir lanoline.",
    "acides de lanoline",
    "acides de lanoline",
    "graisse de laine",
    "cire de laine",
    "linoléate de lanoline",
    "huile de lanoline",
    "ricinoléate de lanoline",
    "cire de lanoline",
    "lanoline(e)",
    "lanoline : acide lanoline",
    "lanostérol",
    "lanostérol : voir lanoline.",
    "lanostérols",
    "saindoux",
    "glycéride de saindoux",
    "protéine animale hydrolysée au laurol",
    "cuir",
    "cuir suédé, peau de veau, peau de mouton, peau d'alligator, autres types de peau",
    "lécithine cholinebitartrate",
    "leucine",
    "acide linoléique",
    "lipase",
    "lipides",
    "lipoïdes",
    "lipides",
    "foie",
    "extrait de foie",
    "pâté de foie",
    "homard",
    "lait écrémé",
    "yaourt à faible teneur en matières grasses",
    "lunasponge",
    "luncehon loaf",
    "viandes de déjeuner",
    "viandes de déjeuner",
    "lysine",
    "maquereau",
    "caséinate de magnésium",
    "lait malté",
    "extrait de mammifère",
    "huile marine",
    "soupe à la moelle",
    "mayonnaise",
    "protéines animales hydrolysées",
    "viande",
    "pain de viande",
    "boulette de viande",
    "poulet séparé mécaniquement",
    "méthionine",
    "mettwurst",
    "lait",
    "chocolat au lait",
    "dérivé du lait",
    "lait de mammifères",
    "protéine de lait",
    "peau de lait",
    "sucre du lait",
    "matière grasse du lait",
    "poudre de lait",
    "viande de boeuf hachée",
    "viande hachée",
    "huile de vison",
    "minkamidopropyl diethylamine",
    "mohair",
    "mollusques et crustacés",
    "baudroie",
    "mono- et di-glycérides",
    "monoglycérides glycérides",
    "glycérides monoglycérides (voir glycérine)",
    "orignal",
    "mortadelle",
    "huile de mossbunker",
    "mulet",
    "extrait de muscle",
    "musc",
    "musc (huile)",
    "musc ambrette",
    "moule",
    "moules",
    "mouton",
    "sulfate d'éther de myristal",
    "acide myristalique",
    "acide myristique",
    "protéine animale hydrolysée myristoyle",
    "myristyle",
    "myristyles",
    "arôme naturel de beurre",
    "arômes naturels",
    "rouge naturel 4",
    "sources naturelles",
    "cou",
    "lait écrémé",
    "note :",
    "nougat",
    "acides nucléiques",
    "océnol",
    "octopus",
    "octyl dodecanol",
    "huiles",
    "oléamidopropyl diméthylamine, protéine animale hydrolysée",
    "acide oléique",
    "huile oléique",
    "oléostéarine",
    "oléostéarine",
    "protéine animale hydrolysée à l'oléoyle",
    "oléthes",
    "arachidate d'oléyle",
    "oleyl betatine",
    "oleyl imidazoline",
    "oleyl lanolate",
    "oleyl myristate",
    "oléyl oleate",
    "stéarate d'oléyle",
    "oleylalcohol ocenol",
    "oleylimidazoline",
    "acides gras oméga-3",
    "opossum",
    "organes",
    "organes",
    "organes",
    "autruche",
    "ovalbumine",
    "extrait d'ovaire",
    "bile de boeuf",
    "oxgall",
    "huître",
    "palmitamide",
    "palmitamine",
    "palmitate",
    "acide palmitique",
    "protéine de lait hydrolysée au palmitoyl",
    "protéine animale hydrolysée au palmitoyl",
    "pancetta",
    "panthénol",
    "panthényle",
    "paracaséine",
    "perdrix",
    "lait pasteurisé",
    "perle",
    "essence de perle",
    "pentahydrosqualène",
    "pepsine",
    "perhydrosqualène",
    "vernis pharmaceutique",
    "faisan",
    "épaule de pique-nique",
    "extrait de peau de porc",
    "placenta",
    "protéine polypeptidique du placenta après la naissance",
    "protéine polypeptidique du placenta",
    "enzymes placentaires",
    "extrait placentaire",
    "protéine placentaire",
    "plie",
    "huile de pogy",
    "colin",
    "éther cétylique de polyéthylène",
    "polyglycérol",
    "éther d'alcool de polyglycéryle-2lanoline",
    "polypeptides",
    "protéines polypeptidiques",
    "polysorbates",
    "polytétylène glycérol/glycol/peg",
    "pancréas porcin",
    "porc",
    "graisse de porc",
    "rouleau de porc",
    "caséinate de potassium",
    "protéine animale hydrolysée au potassium undecylenoyl",
    "volaille",
    "lanoline ppg-12-peg-50",
    "éthers d'alcool de lanoline ppg-2,-5, -10. -20, -30",
    "éther de lanoline ppg-30",
    "crevette",
    "acétate de prégnénolone",
    "pristane",
    "progestérone",
    "propolis",
    "prosciutto",
    "provitamine A",
    "provitamine B-5",
    "provitamine D-2",
    "huile de purcelline syn",
    "caille",
    "quaternium 27",
    "lapin",
    "viande rouge",
    "lait à teneur réduite en matières grasses",
    "yaourt à teneur réduite en matières grasses",
    "présure",
    "caséine présure",
    "caillette",
    "rennine",
    "glaçage résineux",
    "réticuline",
    "rétinol",
    "acide ribonucléique",
    "acide ribonucléique rna",
    "roast beef",
    "rôti de porc",
    "roe",
    "gelée royale",
    "zibeline",
    "brosses de zibeline",
    "hydrolysat de saccharides",
    "isomérat de saccharide",
    "salami",
    "salceson",
    "saumon",
    "sardine",
    "saucisse",
    "saucisses",
    "coquille Saint-Jacques",
    "coquilles Saint-Jacques",
    "éponge de mer",
    "huile de tortue de mer",
    "éponge de mer",
    "sérum albumine",
    "protéines sériques",
    "huile de foie de requin",
    "huile de foie de requin",
    "lait de brebis",
    "peau de mouton",
    "gomme-laque",
    "vernis résineux à la gomme-laque",
    "cire de gomme-laque",
    "épaule",
    "crevette",
    "crevette",
    "bacon de côté",
    "soie",
    "acides aminés de soie",
    "poudre de soie",
    "poudre de soie",
    "lait écrémé",
    "bacon en tranches",
    "viandes en tranches",
    "jambon fumé",
    "escargot",
    "escargots",
    "serpent",
    "vivaneau",
    "protéines animales hydrolysées sodium / thé-lauroyl",
    "protéines animales hydrolysées sodium / thé-undécylénoyl",
    "caséinate de sodium",
    "protéine animale hydrolysée au coco de sodium",
    "protéine animale hydrolysée de soja sodique",
    "sulfate de suif de sodium",
    "tallowate de sodium",
    "undécylénate de sodium",
    "sodiumsteroyl lactylate",
    "collagène soluble",
    "crème aigre",
    "lait aigre",
    "solides du lait aigre",
    "lait aigre",
    "hydroxyéthylimidazoline de soja",
    "huile de sperme",
    "intestins de cachalot",
    "spermaceti",
    "huile de sperme palmitate de spermaceticyle",
    "extrait de rate",
    "éponge (de lune et de mer)",
    "pigeonneau",
    "squalane",
    "squalène",
    "calmar",
    "écureuil",
    "steak",
    "stéaramide",
    "stéaramine",
    "oxyde de stéaramine",
    "stéarates",
    "acide stéarique",
    "hydrazide stéarique",
    "stéarine",
    "stéarone",
    "stéaroxytriméthylsilane",
    "acide stéaroyl lactylique",
    "acétate de stéaryle",
    "stérols d'alcool stéarylique",
    "stéaryl betaine",
    "caprylate de stéaryle",
    "citrate de stéaryle",
    "glycyrrhétinate de stéaryle",
    "heptanoate de stéaryle",
    "imidazoline de stéaryle",
    "octanoate de stéaryle",
    "stéaryl stearate",
    "stearyldimethyl amine",
    "stéroïdes stérols",
    "stérols",
    "steak à ragoût",
    "stilton",
    "streaky bacon",
    "daim",
    "lactosérum doux",
    "petit-lait doux",
    "ris de veau",
    "lait condensé sucré",
    "espadon",
    "suif",
    "acide de suif",
    "amide de suif",
    "tallow amine",
    "oxyde de suif aminé",
    "alcool gras de suif",
    "glycérides de suif",
    "hydroxyéthal imidazoline de suif",
    "imidazoline de suif",
    "alcool gras de suif, acide stéarique",
    "chlorure de trimonium de suif - suif",
    "oxyde de suifamidopropylamine",
    "talloweth-6",
    "tallowmide dea and mea",
    "tallowmidopropyl hydroxysultaine",
    "tallowminopropylamine",
    "tallowmphoacete",
    "tea-coco protéine animale hydrolysée",
    "acides aminés de collagène animal tea-lauroyl",
    "acides aminés de kératine animale du thé-lauroyl",
    "protéine animale hydrolysée par le thé-undécylénoyl",
    "extrait testiculaire",
    "thréonine",
    "saucisse de thuringe",
    "tilapia",
    "langue",
    "éthosulfate de triéthonium de protéines animales hydrolysées",
    "trilaneth-4phosphate",
    "tripes",
    "alcools triterpéniques",
    "truite",
    "trypsine",
    "thon",
    "dinde",
    "bacon de dinde",
    "poitrine de dinde",
    "tortue",
    "huile de tortue",
    "huile de tortue de mer",
    "tyrosine",
    "lait non-homogénéisé",
    "urée",
    "carbamide d'urée",
    "acide urique",
    "acide urique de vache",
    "acide urique",
    "urine",
    "veau",
    "pain de veau",
    "venaison",
    "vitamine A",
    "vitamine b-complexe facteur",
    "vitamine d ergocalciférol vitamine d",
    "vitamine d3",
    "vitamine h",
    "vitamine b",
    "facteur vitaminique B",
    "volaise",
    "lactosérum",
    "poudre de lactosérum",
    "protéine de lactosérum",
    "crème fouettée",
    "garniture fouettée",
    "viande blanche",
    "lait entier",
    "yaourt au lait entier",
    "sanglier",
    "viande sauvage",
    "laine",
    "laine grasse",
    "cire de laine",
    "alcools de cire de laine",
    "yoghourt",
    "yaourt",
    "caséinate de zinc",
    "protéines animales hydrolysées au zinc",
    "boeuf",
    "agneau",
    "porc",
    "veau",
    "cheval",
    "organe",
    "viande",
    "cuir",
    //Poultry
    "poulet",
    "dinde",
    "oie",
    "canard",
    "caille",
    "saumon",
    "morue",
    "hareng",
    "Mahi-mahi",
    "poisson",
    "maquereau",
    "perche",
    "truite",
    "sardine",
    "thon",
    "goberge",
    "omble chevalier",
    "lait",
    "yahourt",
    "fromage",
    "beure",
    "crème",
    "crème glacée",
    //Produits d'abeille
    "miel",
    "pollen",
    "gelée royale",
  ],
};
