name: CI - Test the branches

on:
  push:
    branches-ignore:
      - develop
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      - name: Install nvm
        uses: dcodeIO/setup-node-nvm@master
        with:
          node-version: "14.15.0"

      - name: Install the dependencies
        run: yarn
      
      - name : setup the db
        run : yarn setup-test-db

      - name: Run the tests
        run: yarn test

      - name : Build
        run: yarn build